# -*- coding: utf-8 -*-
"""setup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EVOTnpvluJ__I8u6T8w40WkSEs6iBo-q
"""

# 必要なモジュールのインストール/インポート
import torch
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
! pip install fugashi ipadic
! pip install unidic_lite
import numpy as np
import os
import gdown

# フォルダIDを指定
folder_id = "1YmF_3TihtXOEELXUr_ShG1kT4rIIzgef"

# ダウンロード先ディレクトリ
save_dir = "/content/trained_model"
os.makedirs(save_dir, exist_ok=True)

# gdownを使ってフォルダ全体をダウンロード
gdown.download_folder(f"https://drive.google.com/drive/folders/{folder_id}", output=save_dir, quiet=False)

# モデルとトークナイザを読み込み
from transformers import AutoModelForSequenceClassification, AutoTokenizer
loaded_model = AutoModelForSequenceClassification.from_pretrained(save_dir)
loaded_tokenizer = AutoTokenizer.from_pretrained(save_dir)

# デバイスを指定
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
loaded_model.to(device)

